Feature/add manual definition input
mwhitman189/yambo-flashcards pull request #20
Opened 2022-07-27 06:18 UTC by justjohnd

Made the following changes based on the design below:
1. Front and Back textarea fields should allow for manual entry and display in real time on the Preview card below
2. "Save | Clear" options should appear as soon as anything is entered into the front of the card
3. Pushing "Auto-Generate" should make an API call and populate the back of the card with information (or flash an error message)
4. Pushing "Save" should save the item to the "Deck" component below. (Currently, user will only see the number of cards saved so far).

- "Decks" input field and "Set" checkbox have been added, but don't have functionality yet.
- No substantial tests have been written for the component yet.

![image](https://user-images.githubusercontent.com/55176130/181174505-96bac77e-a6f3-4ecd-a50d-4d80b11362c2.png)

2022-07-27 12:23 UTC, mwhitman189 requested changes
You got it all looking and working according to the specs. If you just address the issues here I'll merge the changes. Thanks!

2022-07-27 12:23 UTC, mwhitman189 commented on yambo-front/src/components/CardCreate.tsx
> +import { TailSpin } from "react-loader-spinner";
This does not appear to be in package.json. I think you either installed it globally, or installed without the "--save" flag, which is causing the test to fail.

2022-07-27 12:23 UTC, mwhitman189 commented on package.json
>  }
There's no new spinner library in package.json.
Try `npm i react-loader-spinner --save` to add it to "depenencies"

2022-07-27 12:23 UTC, mwhitman189 commented on yambo-front/src/components/CardCreate.tsx
>        const fetchData = async () => {
After the fetch call, you can check whether or not the response returned with a status of 200:
        if (response.status === 200) {
then continue setting the card data. And you could move the spinner outside of the         if (response.status === 200) {} so you only have to call setLoader(false) once.

2022-07-28 03:13 UTC, justjohnd commented
- Add react-loader-spinner
- Adjust position of "Word Not Found" alert
- Modify "back" tab disable functionality. Not tab is only disabled until user clicks in either of the textareas
- Make "Front" textarea required

2022-07-29 12:31 UTC, mwhitman189 approved these changes

2022-07-29 12:33 UTC, merged